apiVersion: apps/v1
kind: Deployment
metadata:
  name: spahtmx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spahtmx
  template:
    metadata:
      labels:
        app: spahtmx
    spec:
      containers:
      - name: spahtmx
        image: spahtmx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
